name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # - name: Use cached node_modules
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: nodeModules-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       nodeModules-

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.5.2

      - name: Install dependencies
        run: pnpm install
        env:
          CI: true

      - name: Lint
        run: pnpm lint
        env:
          CI: true

      - name: Test
        run: pnpm test
        env:
          CI: true

      - name: Build
        run: pnpm build
        env:
          CI: true
